package com.bombaylive.chancecrest.game.model;
import javax.persistence.*;
import lombok.*;
import java.time.LocalDateTime;

/**
 * Represents
 * gaming session data, including bet amount, player-selected number, server-generated number, winning amount, and timestamp
 */
@Data
@Builder
@NoArgsConstructor
@AllArgsConstructor
@Entity
@Table(name = "game_session")
public class GameSession {

    /**
     * Unique identifier for the game session.
     */
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    @Column(name = "id", nullable = false, updatable = false)
    private Long id;

    /**
     * Amount placed as bet by the player.
     */
    @Column(name = "bet_amount", nullable = false)
    private double betAmount;

    /**
     * The number chosen by the player.
     */
    @Column(name = "player_number", nullable = false)
    private int playerNumber;

    /**
     * The number randomly generated by the server for the game session.
     */
    @Column(name = "server_generated_number", nullable = false)
    private int serverGeneratedNumber;

    /**
     * The amount won by the player.
     */
    @Column(name = "win_amount", nullable = false)
    private double winAmount;

    /**
     * The timestamp when the game session was played.
     */
    @Column(name = "played_at", nullable = false)
    private LocalDateTime playedAt = LocalDateTime.now();

}
